---
version: '3'
services:
  sqldb:
    image: mysql:8.0.17
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    volumes:
      - ../resources/Data.sql:/docker-entrypoint-initdb.d/init.sql
